### ISSUE TITLE
withdraw() doesn't follow check-state-send

### ISSUE THREAD

**Issue by veox** [dsystems-io/childDaoWithdraw#4]
[infiltratedChildWithdraw.sol:L64](https://github.com/dsystems-io/childDaoWithdraw/commit/336025a627f582e5d6bb459f0d0775d1600a9dbc#diff-0a4069f1c25cbb49810c698fc5e0c061R64):

```
function withdraw() notWithdrawn isCurator isSufficient returns (bool success) {
    for(uint i=0; i<withdrawWhiteList.length; i++) {
      if(!withdrawWhiteList[i].send(withdrawValue[i])) throw;
    }
    isWithdrawn = true;
    return true;
}
```

Although the other modifiers are probably sufficient protection, if would still be nice to see `isWithdrawn = true` moved before the loop.

**Comment by paulszczesny** [comment]
This is a good idea. The only downside is that if the contract fails, a new one needs to be deployed. Small trade-off though against the possibility of a double transaction mistake.
