### ISSUE TITLE
Refundees must be notified to use external accounts or simple wallets

### ISSUE THREAD

**Issue by veox** [dsystems-io/childDaoWithdraw#5]
All three dapps use `send()` for refunds.

To prevent possible lock-up (especially from `infiltratedChildWithdraw`), it is paramount that users be notified of the fact.

Perhaps also verify that the most commonly used wallets are not doing something expensive in their fallbacks.

**Comment by paulszczesny** [comment]
This is most crucial for `infiltratedChildWithdraw`. The other 2 contracts require that the childDAO token holders themselves initiate the withdrawal so they absolutely must be notified in order to receive funds at all. I hope the curators are able to communicate this message effectively.

**Comment by paulszczesny** [comment]
Perhaps a suicide call with time delay would be appropriate. Whereby the curators could suicide the contract only after block #3,000,000.
